### PR TITLE
Remove 118 duplicate terms

### PR DESCRIPTION
**Pull request by rays22**
1.
- remove entity_attribute.tsv
4264:OBA:2060161                UBERON:0005487  vitelline vein  PATO:0000051    morphology
* keep
entity_attribute_part_of.tsv
1675:OBA:0005143                UBERON:0005487  vitelline vein  PATO:0000051    morphology
2.
- remove
entity_attribute.tsv
4245:OBA:2060142                UBERON:0000014  zone of skin    PATO:0000051    morphology
* keep
entity_attribute_part_of.tsv
341:OBA:VT0002096       skin morphology trait   UBERON:0000014  zone of skin    PATO:0000051    morphology
3.
- remove
entity_attribute.tsv
4130:OBA:2060027                UBERON:0001798  vitreous body   PATO:0000051    morphology
* keep
entity_attribute_part_of.tsv
489:OBA:VT0002699       vitreous body morphology trait  UBERON:0001798  vitreous body   PATO:0000051    morphology

This is related to #192.

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
I approve if none of these classes where ever in a release

**Comment by rays22** [comment]
> I approve if none of these classes where ever in a release

They are quite new. I have checked them and they are not in the latest release. 

There is also another batch of 115 duplicates to be fixed:


remove | keep | defined_class_name | entity | entity_name | attribute | attribute_name | defined_class
-- | -- | -- | -- | -- | -- | -- | --
OBA:2060022 | OBA:VT0003257 | abdominal wall morphology trait | UBERON:0003697 | abdominal wall | PATO:0000051 | morphology | OBA:VT0003257
OBA:2060023 | OBA:VT0000886 | cerebellar granule layer morphology trait | UBERON:0002956 | granular layer of cerebellar cortex | PATO:0000051 | morphology | OBA:VT0000886
OBA:2060024 | OBA:VT0000367 | coat/hair morphology trait | UBERON:0001037 | strand of hair | PATO:0000051 | morphology | OBA:VT0000367
OBA:2060025 | OBA:VT0003005 | hippocampus fimbria morphology trait | UBERON:0002310 | hippocampus fimbria | PATO:0000051 | morphology | OBA:VT0003005
OBA:2060026 | OBA:VT0006215 | optic disc morphology trait | UBERON:0001783 | optic disc | PATO:0000051 | morphology | OBA:VT0006215
OBA:2060046 | OBA:VT0001726 | allantois morphology trait | UBERON:0004340 | allantois | PATO:0000051 | morphology | OBA:VT0001726
OBA:2060047 | OBA:VT0000818 | amygdala morphology trait | UBERON:0001876 | amygdala | PATO:0000051 | morphology | OBA:VT0000818
OBA:2060048 | OBA:0004331 |   | UBERON:0000935 | anterior commissure | PATO:0000051 | morphology | OBA:0004331
OBA:2060049 | OBA:VT0000272 | aorta morphology trait | UBERON:0000947 | aorta | PATO:0000051 | morphology | OBA:VT0000272
OBA:2060050 | OBA:VT0000572 | autopod morphology trait | UBERON:0002470 | autopod region | PATO:0000051 | morphology | OBA:VT0000572
OBA:2060051 | OBA:VT0001614 | blood vessel morphology trait | UBERON:0001981 | blood vessel | PATO:0000051 | morphology | OBA:VT0001614
OBA:2060052 | OBA:VT0003385 | body wall morphology trait | UBERON:0000309 | body wall | PATO:0000051 | morphology | OBA:VT0003385
OBA:2060053 | OBA:0003393 |   | UBERON:0008867 | trabecular network of bone | PATO:0000051 | morphology | OBA:0003393
OBA:2060054 | OBA:0004307 |   | UBERON:0001887 | internal capsule of telencephalon | PATO:0000051 | morphology | OBA:0004307
OBA:2060055 | OBA:VT0002152 | brain morphology trait | UBERON:0000955 | brain | PATO:0000051 | morphology | OBA:VT0002152
OBA:2060056 | OBA:VT0002759 | caudal vertebra morphology trait | UBERON:0001095 | caudal vertebra | PATO:0000051 | morphology | OBA:VT0002759
OBA:2060057 | OBA:0004942 |   | UBERON:0002132 | dentate nucleus | PATO:0000051 | morphology | OBA:0004942
OBA:2060058 | OBA:0004946 |   | UBERON:0004073 | cerebellum interpositus nucleus | PATO:0000051 | morphology | OBA:0004946
OBA:2060059 | OBA:0003760 |   | UBERON:0002413 | cervical vertebra | PATO:0000051 | morphology | OBA:0003760
OBA:2060060 | OBA:VT0004167 | cingulate gyrus morphology trait | UBERON:0002967 | cingulate gyrus | PATO:0000051 | morphology | OBA:VT0004167
OBA:2060061 | OBA:VT0005298 | clavicle morphology trait | UBERON:0001105 | clavicle bone | PATO:0000051 | morphology | OBA:VT0005298
OBA:2060062 | OBA:0003645 |   | UBERON:0010166 | coat of hair | PATO:0000051 | morphology | OBA:0003645
OBA:2060063 | OBA:VT0001312 | cornea morphology trait | UBERON:0000964 | cornea | PATO:0000051 | morphology | OBA:VT0001312
OBA:2060064 | OBA:VT0000780 | corpus callosum morphology trait | UBERON:0002336 | corpus callosum | PATO:0000051 | morphology | OBA:VT0000780
OBA:2060065 | OBA:VT0002878 | corticospinal tract morphology trait | UBERON:0002707 | corticospinal tract | PATO:0000051 | morphology | OBA:VT0002878
OBA:2060066 | OBA:VT0010612 | cranium morphology | UBERON:0003128 | cranium | PATO:0000051 | morphology | OBA:VT0010612
OBA:2060067 | OBA:VT0000812 | dentate gyrus morphology trait | UBERON:0001885 | dentate gyrus of hippocampal formation | PATO:0000051 | morphology | OBA:VT0000812
OBA:2060068 | OBA:VT0002279 | diaphragm morphology trait | UBERON:0001103 | diaphragm | PATO:0000051 | morphology | OBA:VT0002279
OBA:2060069 | OBA:VT0000462 | gastrointestinal system morphology trait | UBERON:0001007 | digestive system | PATO:0000051 | morphology | OBA:VT0000462
OBA:2060070 | OBA:VT0002110 | digit morphology trait | UBERON:0002544 | digit | PATO:0000051 | morphology | OBA:VT0002110
OBA:2060071 | OBA:VT0002102 | ear morphology trait | UBERON:0001690 | ear | PATO:0000051 | morphology | OBA:VT0002102
OBA:2060073 | OBA:0003774 |   | UBERON:0005056 | external female genitalia | PATO:0000051 | morphology | OBA:0003774
OBA:2060074 | OBA:0004644 |   | UBERON:0004053 | external male genitalia | PATO:0000051 | morphology | OBA:0004644
OBA:2060075 | OBA:VT0002086 | extraembryonic tissue morphology trait | UBERON:0000478 | extraembryonic structure | PATO:0000051 | morphology | OBA:VT0002086
OBA:2060077 | OBA:VT0001340 | eyelid morphology trait | UBERON:0001711 | eyelid | PATO:0000051 | morphology | OBA:VT0001340
OBA:2060078 | OBA:VT0003743 | facial morphology trait | UBERON:0001456 | face | PATO:0000051 | morphology | OBA:VT0003743
OBA:2060079 | OBA:VT0001071 | facial nerve morphology trait | UBERON:0001647 | facial nerve | PATO:0000051 | morphology | OBA:VT0001071
OBA:2060080 | OBA:0004650 |   | UBERON:0003134 | female reproductive organ | PATO:0000051 | morphology | OBA:0004650
OBA:2060081 | OBA:VT0000559 | femur morphology trait | UBERON:0000981 | femur | PATO:0000051 | morphology | OBA:VT0000559
OBA:2060082 | OBA:VT0002187 | fibula morphology trait | UBERON:0001446 | fibula | PATO:0000051 | morphology | OBA:VT0002187
OBA:2060083 | OBA:VT0000574 | foot pad morphology trait | UBERON:0008838 | metapodial pad | PATO:0000051 | morphology | OBA:VT0000574
OBA:2060084 | OBA:VT0000783 | forebrain morphology trait | UBERON:0001890 | forebrain | PATO:0000051 | morphology | OBA:VT0000783
OBA:2060085 | OBA:VT0000550 | forelimb morphology trait | UBERON:0002102 | forelimb | PATO:0000051 | morphology | OBA:VT0000550
OBA:2060086 | OBA:VT0000828 | fourth ventricle morphology trait | UBERON:0002422 | fourth ventricle | PATO:0000051 | morphology | OBA:VT0000828
OBA:2060087 | OBA:VT0004082 | habenula morphology trait | UBERON:0001904 | habenula | PATO:0000051 | morphology | OBA:VT0004082
OBA:2060088 | OBA:VT0000432 | head morphology trait | UBERON:0000033 | head | PATO:0000051 | morphology | OBA:VT0000432
OBA:2060089 | OBA:VT0003921 | left ventricle morphology trait | UBERON:0002084 | heart left ventricle | PATO:0000051 | morphology | OBA:VT0003921
OBA:2060090 | OBA:VT0000266 | heart morphology trait | UBERON:0000948 | heart | PATO:0000051 | morphology | OBA:VT0000266
OBA:2060091 | OBA:VT0000841 | hindbrain morphology trait | UBERON:0002028 | hindbrain | PATO:0000051 | morphology | OBA:VT0000841
OBA:2060092 | OBA:VT0000556 | hindlimb morphology trait | UBERON:0002103 | hindlimb | PATO:0000051 | morphology | OBA:VT0000556
OBA:2060093 | OBA:0004328 |   | UBERON:0000908 | hippocampal commissure | PATO:0000051 | morphology | OBA:0004328
OBA:2060094 | OBA:0004353 |   | UBERON:0005368 | hippocampus molecular layer | PATO:0000051 | morphology | OBA:0004353
OBA:2060095 | OBA:0005318 |   | UBERON:0005371 | hippocampus stratum oriens | PATO:0000051 | morphology | OBA:0005318
OBA:2060096 | OBA:0005319 |   | UBERON:0005372 | hippocampus stratum radiatum | PATO:0000051 | morphology | OBA:0005319
OBA:2060097 | OBA:VT0005296 | humerus morphology trait | UBERON:0000976 | humerus | PATO:0000051 | morphology | OBA:VT0005296
OBA:2060098 | OBA:VT0005358 | incisor morphology trait | UBERON:0001098 | incisor tooth | PATO:0000051 | morphology | OBA:VT0005358
OBA:2060099 | OBA:VT0001322 | iris morphology trait | UBERON:0001769 | iris | PATO:0000051 | morphology | OBA:VT0001322
OBA:2060100 | OBA:0003754 |   | UBERON:0000982 | skeletal joint | PATO:0000051 | morphology | OBA:0003754
OBA:2060101 | OBA:VT0000823 | lateral ventricle morphology trait | UBERON:0002285 | telencephalic ventricle | PATO:0000051 | morphology | OBA:VT0000823
OBA:2060102 | OBA:VT0001303 | lens morphology trait | UBERON:0000965 | lens of camera-type eye | PATO:0000051 | morphology | OBA:VT0001303
OBA:2060103 | OBA:VT0005650 | limb bud morphology trait | UBERON:0004347 | limb bud | PATO:0000051 | morphology | OBA:VT0005650
OBA:2060104 | OBA:VT0002109 | limb morphology trait | UBERON:0002101 | limb | PATO:0000051 | morphology | OBA:VT0002109
OBA:2060105 | OBA:VT0003769 | lip morphology trait | UBERON:0001833 | lip | PATO:0000051 | morphology | OBA:VT0003769
OBA:2060106 | OBA:VT0000598 | liver morphology trait | UBERON:0002107 | liver | PATO:0000051 | morphology | OBA:VT0000598
OBA:2060107 | OBA:VT0010494 | lumbar vertebra morphology trait | UBERON:0002414 | lumbar vertebra | PATO:0000051 | morphology | OBA:VT0010494
OBA:2060108 | OBA:VT0001175 | lung morphology trait | UBERON:0002048 | lung | PATO:0000051 | morphology | OBA:VT0001175
OBA:2060109 | OBA:0004643 |   | UBERON:0003135 | male reproductive organ | PATO:0000051 | morphology | OBA:0004643
OBA:2060110 | OBA:0005653 |   | UBERON:0002990 | mammillothalamic tract of hypothalamus | PATO:0000051 | morphology | OBA:0005653
OBA:2060111 | OBA:0003504 |   | UBERON:0001684 | mandible | PATO:0000051 | morphology | OBA:0003504
OBA:2060112 | OBA:VT0000455 | maxilla morphology trait | UBERON:0002397 | maxilla | PATO:0000051 | morphology | OBA:VT0000455
OBA:2060113 | OBA:VT0000897 | midbrain morphology trait | UBERON:0001891 | midbrain | PATO:0000051 | morphology | OBA:VT0000897
OBA:2060114 | OBA:VT0000452 | mouth morphology trait | UBERON:0000165 | mouth | PATO:0000051 | morphology | OBA:VT0000452
OBA:2060115 | OBA:VT0000579 | nail morphology trait | UBERON:0001705 | nail | PATO:0000051 | morphology | OBA:VT0000579
OBA:2060116 | OBA:0005365 |   | UBERON:0005062 | neural fold | PATO:0000051 | morphology | OBA:0005365
OBA:2060117 | OBA:1001054 |   | UBERON:0001049 | neural tube | PATO:0000051 | morphology | OBA:1001054
OBA:2060118 | OBA:VT0004267 | optic tract morphology trait | UBERON:0001908 | optic tract | PATO:0000051 | morphology | OBA:VT0004267
OBA:2060119 | OBA:VT0005246 | orbit morphology trait | UBERON:0001697 | orbit of skull | PATO:0000051 | morphology | OBA:VT0005246
OBA:2060120 | OBA:VT0006030 | otic vesicle morphology trait | UBERON:0003051 | ear vesicle | PATO:0000051 | morphology | OBA:VT0006030
OBA:2060121 | OBA:0002845 |   | UBERON:0001691 | external ear | PATO:0000051 | morphology | OBA:0002845
OBA:2060122 | OBA:0003356 |   | UBERON:0007830 | pelvic girdle bone/zone | PATO:0000051 | morphology | OBA:0003356
OBA:2060123 | OBA:VT0000288 | pericardium morphology trait | UBERON:0002407 | pericardium | PATO:0000051 | morphology | OBA:VT0000288
OBA:2060124 | OBA:0003750 |   | UBERON:0002539 | pharyngeal arch | PATO:0000051 | morphology | OBA:0003750
OBA:2060125 | OBA:0004968 |   | UBERON:0004725 | piriform cortex | PATO:0000051 | morphology | OBA:0004968
OBA:2060126 | OBA:VT0001711 | placenta morphology trait | UBERON:0001987 | placenta | PATO:0000051 | morphology | OBA:VT0001711
OBA:2060127 | OBA:VT0000848 | pons morphology trait | UBERON:0000988 | pons | PATO:0000051 | morphology | OBA:VT0000848
OBA:2060128 | OBA:VT0000800 | prefrontal gyrus morphology trait | UBERON:0001384 | primary motor cortex | PATO:0000051 | morphology | OBA:VT0000800
OBA:2060129 | OBA:VT0001317 | pupil morphology trait | UBERON:0001771 | pupil | PATO:0000051 | morphology | OBA:VT0001317
OBA:2060130 | OBA:VT0000552 | radius morphology trait | UBERON:0001423 | radius bone | PATO:0000051 | morphology | OBA:VT0000552
OBA:2060131 | OBA:VT0002160 | reproductive system morphology trait | UBERON:0000990 | reproductive system | PATO:0000051 | morphology | OBA:VT0002160
OBA:2060132 | OBA:VT0002792 | retina blood vessel morphology trait | UBERON:0003501 | retina blood vessel | PATO:0000051 | morphology | OBA:VT0002792
OBA:2060133 | OBA:VT0003733 | retinal inner nuclear layer morphology trait | UBERON:0001791 | inner nuclear layer of retina | PATO:0000051 | morphology | OBA:VT0003733
OBA:2060134 | OBA:VT0001325 | retina morphology trait | UBERON:0000966 | retina | PATO:0000051 | morphology | OBA:VT0001325
OBA:2060135 | OBA:VT0003731 | retinal outer nuclear layer morphology trait | UBERON:0001789 | outer nuclear layer of retina | PATO:0000051 | morphology | OBA:VT0003731
OBA:2060137 | OBA:0005651 |   | UBERON:0014918 | retrosplenial granular cortex | PATO:0000051 | morphology | OBA:0005651
OBA:2060138 | OBA:VT0000150 | rib morphology trait | UBERON:0002228 | rib | PATO:0000051 | morphology | OBA:VT0000150
OBA:2060139 | OBA:0003761 |   | UBERON:0001094 | sacral vertebra | PATO:0000051 | morphology | OBA:0003761
OBA:2060140 | OBA:VT0000149 | scapula morphology trait | UBERON:0006849 | scapula | PATO:0000051 | morphology | OBA:VT0000149
OBA:2060141 | OBA:VT0000863 | secondary somatosensory cortex morphology trait | UBERON:0008934 | secondary somatosensory cortex | PATO:0000051 | morphology | OBA:VT0000863
OBA:2060143 | OBA:VT0000443 | snout morphology trait | UBERON:0006333 | snout | PATO:0000051 | morphology | OBA:VT0000443
OBA:2060144 | OBA:VT0000955 | spinal cord morphology trait | UBERON:0002240 | spinal cord | PATO:0000051 | morphology | OBA:VT0000955
OBA:2060145 | OBA:VT0004077 | striatum morphology trait | UBERON:0002435 | striatum | PATO:0000051 | morphology | OBA:VT0004077
OBA:2060146 | OBA:VT0002861 | tail bud morphology trait | UBERON:0002533 | post-anal tail bud | PATO:0000051 | morphology | OBA:VT0002861
OBA:2060147 | OBA:VT0002111 | tail morphology trait | UBERON:0002415 | tail | PATO:0000051 | morphology | OBA:VT0002111
OBA:2060148 | OBA:VT0001146 | testes morphology trait | UBERON:0000473 | testis | PATO:0000051 | morphology | OBA:VT0001146
OBA:2060149 | OBA:VT0000826 | third ventricle morphology trait | UBERON:0002286 | third ventricle | PATO:0000051 | morphology | OBA:VT0000826
OBA:2060150 | OBA:VT0003047 | thoracic vertebra morphology trait | UBERON:0002347 | thoracic vertebra | PATO:0000051 | morphology | OBA:VT0003047
OBA:2060151 | OBA:VT0000558 | tibia morphology trait | UBERON:0000979 | tibia | PATO:0000051 | morphology | OBA:VT0000558
OBA:2060152 | OBA:VT0002100 | tooth morphology trait | UBERON:0001091 | calcareous tooth | PATO:0000051 | morphology | OBA:VT0002100
OBA:2060153 | OBA:VT0005108 | ulna morphology trait | UBERON:0001424 | ulna | PATO:0000051 | morphology | OBA:VT0005108
OBA:2060154 | OBA:VT0001725 | umbilical cord morphology trait | UBERON:0002331 | umbilical cord | PATO:0000051 | morphology | OBA:VT0001725
OBA:2060155 | OBA:VT0001139 | vagina morphology trait | UBERON:0000996 | vagina | PATO:0000051 | morphology | OBA:VT0001139
OBA:2060156 | OBA:VT0000137 | vertebra morphology trait | UBERON:0002412 | vertebra | PATO:0000051 | morphology | OBA:VT0000137
OBA:2060157 | OBA:0004024 |   | UBERON:0003861 | neural arch | PATO:0000051 | morphology | OBA:0004024
OBA:2060158 | OBA:0003690 |   | UBERON:0011933 | vibrissa unit | PATO:0000051 | morphology | OBA:0003690
OBA:2060162 | OBA:VT0005270 | zygomatic bone morphology trait | UBERON:0001683 | jugal bone | PATO:0000051 | morphology | OBA:VT0005270

**Comment by matentzn** [comment]
Oh man! Sorry about that.. I thought QC would have caught this but it seems not..

**Comment by rays22** [comment]
> Oh man! Sorry about that.. I thought QC would have caught this but it seems not..

No worries, QC did catch them when I merged #192 .

**Comment by rays22** [comment]
There are some QC errors caused by obsolete GO term components.

**Pull request merged**
