### PR TITLE
Added new 'growth factor' terms

### PR DESCRIPTION
**Pull request by ar-ibrahim**
- issue #225

### CODE REVIEW

**Comment by ar-ibrahim** [comment]
QC checks for this PR repeatedly failed. There were several issues identified by QC which I've attempted to resolve. First, I removed a new OBA term which already exists. Then I removed duplicated terms. I then imported the Protein Ontology terms used to construct the new terms. The checks still failed.

**Comment by matentzn** [comment]
There are more than 70 errors still, I think you will need a bit of Ray magic when he is back, but if you dare to fix yourself, you should learn how to run the test pipeline locally, and open this file: reports/oba.owl-obo-report.tsv

Which has most of the errors in it. From what I can see, the main problem is that your biological attribute terms do not currently classify under "OBA:biological attribute" - is there a grouping class for you new terms that you can manually turn into a subclass of OBA:biological attribute?

**Comment by ar-ibrahim** [comment]
These new terms **(growth factors)** can be a subclass of **'protein amount'** [OBA:VT0010120](https://www.ebi.ac.uk/ols4/ontologies/oba/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FOBA_VT0010120?lang=en).

**Comment by matentzn** [comment]
Are they all just a flat list under that class? you will have to open protege and manually make the top level classes of your newly added classes children of protein amount

**Comment by ar-ibrahim** [comment]
In Protege the new terms are all children of 'amount'. It's more accurate that they should be subclasses of 'protein amount'. There are a total of 63 new terms. So in Protege in 'Subclass of', do I manually add 'protein amount' to all these terms?

**Comment by matentzn** [comment]
If they are a flat list, then yes; but it would be better if you had a grouping class for your new terms, like "growth factor attribute" - then you can simply make that a subclass of protein amount, and the rest will automatically classify under "growth factor attribute".

**Comment by ar-ibrahim** [comment]
Not exactly sure how to do that.

**Comment by matentzn** [comment]
Ok, I fixed all but two errors (which required adding a bunch of PRO terms to our PRO slim). These two need fixing from your side:

- [ ] OBA:2050131	and	OBA:2050134	use the same PRO term, while one is an isoform
- [ ] OBA:2050145	and	OBA:2050182	use the same PRO term

**Comment by ar-ibrahim** [comment]
I think the QC fail this time is because after reviewing all the entity PRO terms, I replaced the entity term (PR:000032046) for (OBA:2050177 transforming growth factor beta receptor type 3 amount) with the more accurate term (PR:Q03167), so an updated import is needed.

**Comment by matentzn** [comment]
Cool checking it. Thanks!

**Pull request merged**
