### PR TITLE
Update definitions for new release

### PR DESCRIPTION
**Pull request by rays22**

### CODE REVIEW

**Comment by shawntanzk** [comment]
super strange that I can review this lol, I have never used this ontology before lol - not sure I can review this as I'm not sure what is going on, happy to if you provide a description?

**Comment by rays22** [comment]
> super strange that I can review this lol, I have never used this ontology before lol - not sure I can review this as I'm not sure what is going on, happy to if you provide a description?

@shawntanzk  I am running a release and it should be [similar to other ODK ontology releases](http://pato-ontology.github.io/pato/odk-workflows/ReleaseWorkflow/). That is why I thought that you could review this PR.
This PR is part of the release process in that it is about updating the definitions for this ontology.

**Comment by shawntanzk** [comment]
ah alright - just didnt know if you edited something in patterns or something - that part I have no idea how to review, if its automated processes, it looks fine, is there a reason these arent updated with the normal release pipeline?

**Review by shawntanzk — APPROVED** [review]

**Comment by rays22** [comment]
> ah alright - just didnt know if you edited something in patterns or something - that part I have no idea how to review, if its automated processes, it looks fine, is there a reason these arent updated with the normal release pipeline?

Nico suggested to put this step (and the next step of refreshing imports) in a separate PR to make troubleshooting easier if there were any problems later in the process.

**Pull request merged**
