### PR TITLE
Add PATO attribute-value SSSOM mapping

### LINKED ISSUE #235: Add Mapping of PATO attributes to PATO attribute values
In order to generate _direct_ mappings from phenotypic effects (abnormally increased blood glucose levels) to their respective OBA classes (blood glucose level), we need to map all fillers in both to each other. This is easy for blood and glucose, because they will be identical in both cases. However, the PATO quality would is different: In the phenotypic effect it would be "increased amount" while in the OBA class, it would be simply "amount". In order to go from "increased amount" to "amount" seamlessly, we need a map that connects the two.

### PR DESCRIPTION
**Pull request by matentzn**
This will help with direct phenotype - trait mappings

Fixes #235

### CODE REVIEW

**Comment by dosumis** [comment]
I have some sense of what it does, but not enough  to review.  Could you describe what this PR does in text - either on the PR or in an linked ticket?

**Comment by matentzn** [comment]
I made a ticket and linked it: https://github.com/obophenotype/bio-attribute-ontology/issues/235

**Comment by dosumis** [comment]
Would like more detail than in current linked ticket

> In order to generate direct mappings from phenotypic effects (abnormally increased blood glucose levels) to their respective OBA classes (blood glucose level), we need to map all fillers in both to each other.

I see a SSSOM file and some SPARQL that seems to be involved in generating it from PATO.  

subject_id |	subject_label	| predicate_id | 	object_id	 | mapping_justification
---|---|---|---|---
PATO:0000303 |	increased speed |	skos:broadMatch |	PATO:0000008|   semapv:UnspecifiedMatching

(PATO:0000008 = speed).

Is this the product that will be used for the intended mapping.  If so, how?  Will there be some kind of convention around interpreting skos:broadMatch in these cases?

**Comment by matentzn** [comment]
The "how" is not at all part of this PR here - we will implement that in a different repo. the only thing that you need to concern yourself with if the mapping is correct, I.E the correct attributes are linked to the correct values. How all of this fits together is a whole different matter - for now we establish:

1. We need to bridge from speed to increased speed to get a direct link (we can't just use rdfs subclass for that for various reasons).
2. We establish the bridge as a sssom file extracted using a sparql query that operates on a mix of logical and lexical assumptions..

Do you have a concern with these last two points looking at this PR?

**Pull request merged**
