### PR TITLE
Added new 'response to chemical' term for GWAS

### PR DESCRIPTION
**Pull request by ar-ibrahim**
- issue #274
- @rays22 does the orcid ID represent the creators of the pattern or the term?

### CODE REVIEW

**Comment by ar-ibrahim** [comment]
@rays22 After updating the chebi slim and importing the chebi term for the new term request, there's a new QC error unrelated to my issue:

```
ERROR	misused_obsolete_label	OBA:0006023	rdfs:label	obsolete proline oxidase activity rate
ERROR	misused_obsolete_label	OBA:1000857	rdfs:label	obsolete proline oxidase activity quality
```

What are your thoughts on this?

**Comment by rays22** [comment]
> ```
> ERROR	misused_obsolete_label	OBA:0006023	rdfs:label	obsolete proline oxidase activity rate
> ERROR	misused_obsolete_label	OBA:1000857	rdfs:label	obsolete proline oxidase activity quality
> ```

@ar-ibrahim ,
In cases like this, when the GO term component becomes obsolete, you need to find an appropriate replacement, or do a manual term edit in Protege.
In the present case, there is a replacement [suggested by GO for GO:0051699](https://www.ebi.ac.uk/QuickGO/term/GO:0051699): [GO:0004657 proline dehydrogenase activity](https://www.ebi.ac.uk/ols4/ontologies/go/classes/http%253A%252F%252Fpurl.obolibrary.org%252Fobo%252FGO_0004657). Replace the occurrences of GO:0051699 with `GO:0004657` in  `entity_attribute.tsv`.

**Comment by rays22** [comment]
> * does the orcid ID represent the creators of the pattern or the term?

It is the ORCID of the contributor of the term.

**Review by rays22 — APPROVED** [review]
Replace the obsolete GO component term in `entity_attribute_part_of.tsv` and `entity_attribute.tsv` and it will be fine.

**Pull request merged**
