### PR TITLE
Added 18 new OBA terms for OBA-EFO mapping

### PR DESCRIPTION
**Pull request by ar-ibrahim**

### CODE REVIEW

**Comment by ar-ibrahim** [comment]
I refreshed the pro slim and merged the new imports but still keep getting a QC error.

**Comment by matentzn** [comment]
What kind of error do you see? It is important for us that you understand the error messages - that is the whole point of having QC :P

**Comment by ar-ibrahim** [comment]
Well the errors I see are in the new terms I created which all have a PRO term as the entity.

**Comment by matentzn** [comment]
Ok, lets break down the error: what does it say?

**Comment by matentzn** [comment]
So, what I would do: open the edit file in Protege, run the reasoner and look at these classes. What do you see? Are all the terms in the logical axioms imported? Does the reasoner perhaps not find a suitable super class?

**Review by rays22 — CHANGES_REQUESTED** [review]
1. I would move the `PR:XXX`-`PATO:0000070 amount `-type traits to the entity_attribute_location.tsv table to make explicit that these attributes are traits of biological organisms or parts of biological organisms as opposed to attributes of a synthetic solution in a test tube or sea water. See the definition of [anatomical entity](https://www.ebi.ac.uk/ols/ontologies/uberon/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FUBERON_0001062&lang=en&viewMode=PreferredRoots&siblings=false)


defined_class | defined_class_name | entity | entity_name | attribute | attribute_name | location | location_name
-- | -- | -- | -- | -- | -- | -- | --
OBA:2050192 | breast cancer anti-estrogen resistance protein 3 amount | PR:000004677 | breast cancer anti-estrogen resistance protein 3 | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050193 | collagen type I alpha chain amount | PR:000003263 | collagen type I alpha chain | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050195 | kidney injury molecule 1 amount | PR:000008453 | hepatitis A virus cellular receptor 1 | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050197 | parathyroid hormone-related protein amount | PR:000013433 | parathyroid hormone-related protein | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050199 | pituitary adenylate cyclase-activating polypeptide amount | PR:000003761 | pituitary adenylate cyclase-activating polypeptide | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050200 | prostate specific antigen amount | PR:000003015 | prostate-specific antigen | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050205 | C-C motif chemokine 17 amount | PR:000001989 | C-C motif chemokine 17 | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050206 | thyroid peroxidase amount | PR:000016584 | thyroid peroxidase | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050207 | tissue plasminogen activator amount | PR:000012825 | tissue-type plasminogen activator | PATO:0000070 | amount | UBERON:0001062 | anatomical entity
OBA:2050208 | tissue factor pathway inhibitor amount | PR:000016279 | tissue factor pathway inhibitor | PATO:0000070 | amount | UBERON:0001062 | anatomical entity


2. I think the QC errors can be fixed by refreshing the imports or merged imports. I have managed to refresh the imports in another PR after solving some laptop memory issues.

**Comment by rays22** [comment]
@ar-ibrahim , before you run the refresh import pipeline (`sh run.sh make imports/merged_import.owl`) try to increase the available memory in your
Docker Desktop  --> Settings --> Resources
to
Memory: 14GB
Swap: 4 GB .
See [Setting memory limits.](https://oboacademy.github.io/obook/howto/odk-setup/#problems-with-memory-important)
I am also going to change the configuration file for the ODK pipeline and decrease the memory allocation for the pipeline to avoid this problem in the future. Running the pipeline may take longer afterwards, but hopefully not too much longer.

**Review by rays22 — APPROVED** [review]

**Pull request merged**
