### PR TITLE
Update entity_attribute.yaml

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Review by matentzn — APPROVED** [review]
Looks good, but I guess we need to try this to be sure your yaml changes work.

I updated the PR, should be merged fast to avoid conflicts

**Comment by matentzn** [comment]
@rays22 to double check with @dosumis in next call and merge.

**Comment by dosumis** [comment]
Looks good to me.  I can't review as I (apparently) opened this PR.

**Comment by dosumis** [comment]
ODK should run basic python checks on branch (I can't see logs as they've expired).  Did you try running a test build with this new YAML?

**Pull request merged**
