### PR TITLE
add rdfs:comment and dfXrefs

### PR DESCRIPTION
**Pull request by megbalk**
issue #137 

also see this [google sheet](https://docs.google.com/spreadsheets/d/1ein2FyM7eUxj3ZuBMJB5GN_4Jp_D31bT8gtaAYnQvuA/edit#gid=0)

### CODE REVIEW

**Review by matentzn — CHANGES_REQUESTED** [review]
Didnt you want to add these columns to the same template we already have? In this PR you are creating a new template table, rather than overwriting the old one and adding the columns.

Also (as an aside): no whitespace in filenames.

**Comment by megbalk** [comment]
ah, I was confused. I thought you said to make a copy. I'll instead add to the existing file.

**Comment by megbalk** [comment]
@matentzn how do the changes look?

**Comment by matentzn** [comment]
Changes seem to have been merged elsewhere.

**Pull request closed without merging**
